version: "3.8"
volumes:
  php-fpm-socket:
  db-store:
services:
  app:
    build:
      context: .
      dockerfile: ./infra/docker/php/Dockerfile
    volumes:
      - php-fpm-socket:/var/run/php-fpm
      - ./backend:/work/backend
    environment:
      - DB_CONNECTION=mysql
      - DB_HOST=127.0.0.1
      - DB_PORT=3306
      - DB_DATABASE=${DB_NAME:-laravel_test}
      - DB_USERNAME=${DB_USER:-test_user}
      - DB_PASSWORD=${DB_PASS:-pass}

  web:
    build:
      context: .
      dockerfile: ./infra/docker/nginx/Dockerfile
    ports:
      - ${WEB_PORT:-80}:80
    volumes:
      - php-fpm-socket:/var/run/php-fpm
      - ./backend:/work/backend

  db:
    build:
      context: .
      dockerfile: ./infra/docker/mysql/Dockerfile
    ports:
      - ${DB_PORT:-3306}:3306
    volumes:
      - db-store:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=${DB_NAME:-laravel_test}
      - MYSQL_USER=${DB_USER:-test_user}
      - MYSQL_PASSWORD=${DB_PASS:-pass}
      - MYSQL_ROOT_PASSWORD=${DB_PASS:-pass}
